<<<<<<< HEAD:DevCodeGroupCapstone/Migrations/201911152331408_nuke3.Designer.cs
﻿// <auto-generated />
namespace DevCodeGroupCapstone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0-preview2-19525-03")]
    public sealed partial class nuke3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nuke3));
        
        string IMigrationMetadata.Id
        {
            get { return "201911152331408_nuke3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
=======
﻿// <auto-generated />
namespace DevCodeGroupCapstone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0-preview2-19525-03")]
    public sealed partial class Init : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Init));
        
        string IMigrationMetadata.Id
        {
            get { return "201911152051078_Init"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
>>>>>>> daca42ebf9cd313b4a6596814722c63e8b282de6:DevCodeGroupCapstone/Migrations/201911152051078_Init.Designer.cs
